apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: aktt1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: aktt1
  labels:
    app: frontend
spec:
  replicas: 1  # You can scale the number of replicas based on your needs
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-sa
      automountServiceAccountToken: false
      containers:
      - name: frontend
        image: lzainzinger02/frontend:1.2.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        securityContext:
          # Disabling privilege escalation
          allowPrivilegeEscalation: false
          # Ensure the container doesn't run with privileged access
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: aktt1
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8086      # The port the service will expose
      targetPort: 80 # The port the container is listening on
  type: LoadBalancer # Change this to LoadBalancer or NodePort if you need external access
