# This are the default values for available configs
name: my-service
namespace: aktt1
replicaCount: 1

image:
  repository: my-docker-repo/my-service
  tag: ""
  pullPolicy: IfNotPresent

containerPort: 3000

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: NodePort
  port: 3001
  nodePort: 30001

serviceAccount:
  name: my-service-sa

configMap:
  enabled: false
  name: my-service-config
  key: products.json