apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service
  namespace: aktt1
data:
  products.json: |
    [
      {"id": 1, "name": "Product A", "price": 100},
      {"id": 2, "name": "Product B", "price": 200}
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: aktt1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: lzainzinger02/product-service:1.1.1
          env:
            - name: PRODUCTS_JSON
              valueFrom:
                configMapKeyRef:
                  name: product-service
                  key: products.json
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: aktt1
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30001  # Exposed NodePort
  type: NodePort
