apiVersion: v1
kind: ConfigMap
metadata:
    name: cart-service
    namespace: aktt1
data:
  # Configuration for cart size limit (optional, if required)
  MAX_CART_SIZE: "100"
  # `cart.json` data to be read by the app
  cart.json: |
    [
      { "productId": 1, "quantity": 2 },
      { "productId": 2, "quantity": 1 }
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: aktt1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: ctadeshsb/cart-service:1.1.0
          env:
            - name: CART_CONFIG_PATH
              value: /etc/config/cart.json  # This should point to where the ConfigMap file is mounted
          volumeMounts:
            - name: cart-config
              mountPath: /etc/config  # Mount the ConfigMap data as a volume
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: cart-config
          configMap:
            name: cart-service
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: aktt1
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3000