apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: aktt1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: lzainzinger02/cart-service:1.2.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: aktt1
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3000
      nodePort: 30002
  type: NodePort