apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.fullnameOverride }}-ingress" # Use fullnameOverride for consistency
  namespace: {{ .Values.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.namespace }}.lzainzinger.com" # Use fullnameOverride
    meta.helm.sh/release-name: {{ .Release.Name }} # Use Release.Name for the release name
    meta.helm.sh/release-namespace: {{ .Release.Namespace }} # Use Release.Namespace for the release namespace
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.namespace }}.lzainzinger.com" # Use fullnameOverride
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.fullnameOverride }}-service # Corrected: Matches the new Service name
            port:
              number: {{ .Values.service.port }}