apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.namespace }}-{{ .Values.fullnameOverride }}-service" # Corrected: Matches the Ingress backend name
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fullnameOverride }} # Ensure this matches your Deployment's pod labels
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }} # This now relies on values.containerPort
  selector:
    app: {{ .Values.fullnameOverride }} # Ensure this matches your Deployment's pod labels
