apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world-sa
  namespace: aktt1
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: aktt1
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      serviceAccountName: hello-world-sa
      automountServiceAccountToken: false
      containers:
      - name: hello-world
        image: lzainzinger02/hello-world:1.2.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          # Disabling privilege escalation
          allowPrivilegeEscalation: false
          # Ensure the container doesn't run with privileged access
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: aktt1
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 80
  type: LoadBalancer
          