apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: aktt1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: lzainzinger02/payment-service:1.1.1  
        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: aktt1
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: NodePort
