namespace: webshop
cart-service:
  name: cart-service
  namespace: webshop
  image:
    repository: lzainzinger02/cart-service
  service:
    port: 3002

payment-service:
  name: payment-service
  namespace: webshop
  image:
    repository: lzainzinger02/payment-service
  service:
    port: 3003

product-service:
  name: product-service
  namespace: webshop
  image:
    repository: lzainzinger02/product-service
  service:
    port: 3001
  configMap:
    enabled: true
    name: product-service

frontend:
  fullnameOverride: frontend # This is used to construct the service name (frontend-service) and hostname (frontend.lzainzinger.com)
  namespace: webshop
  image:
    repository: lzainzinger02/frontend
    tag: "1.4.0"
  service:
    port: 3000 # This is the service's port (what the Ingress connects to)
    nodePort: 30000
  containerPort: 3000 # <-- ADDED: This is the port your frontend application listens on inside its container
