cart-service:
  fullnameOverride: cart-service
  image:
    repository: lzainzinger02/cart-service
    tag: "1.2.0"
  service:
    port: 3002
    type: NodePort
    nodePort: 30002

payment-service:
  fullnameOverride: payment-service
  image:
    repository: lzainzinger02/payment-service
    tag: "1.2.0"
  service:
    port: 3003
    type: NodePort
    nodePort: 30003

product-service:
  fullnameOverride: product-service
  image:
    repository: lzainzinger02/product-service
    tag: "1.2.0"
  service:
    port: 3001
    type: NodePort
    nodePort: 30001

frontend:
  fullnameOverride: frontend
  image:
    repository: lzainzinger02/frontend
    tag: "1.2.0"
  service:
    port: 8086
    type: LoadBalancer
