namespace: webshop
cart-service:
  name: cart-service
  namespace: webshop
  image:
    repository: lzainzinger02/cart-service
  service:
    port: 3002
    nodePort: 30002

payment-service:
  name: payment-service
  namespace: webshop
  image:
    repository: lzainzinger02/payment-service
  service:
    port: 3003
    nodePort: 30003

product-service:
  name: product-service
  namespace: webshop
  image:
    repository: lzainzinger02/product-service
  service:
    port: 3001
    nodePort: 30001
  configMap:
    enabled: true
    name: product-service

frontend:
  fullnameOverride: frontend
  namespace: webshop
  image:
    repository: lzainzinger02/frontend
    tag: "1.2.0"
  service:
    port: 8086
    type: LoadBalancer
